## This yml file is used to sync all the commits into the Organization Repo

name: Mirror to Org Repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code without credentials, full history
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to Org Repo
        env:
          ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
        run: |
          git config --global user.name "Aneesh"
          git config --global user.email "gspamad@gmail.com"

          git remote remove org || echo "No org remote to remove"
          git remote add org https://x-access-token:${ORG_REPO_TOKEN}@github.com/algorand-blockchain-club-vjit/climate-dao.git

          git push org HEAD:main --force
